# Generated by Django 4.1.2 on 2025-03-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free', models.PositiveIntegerField(verbose_name='Свободные места')),
                ('full', models.IntegerField(verbose_name='Занятые места')),
                ('rezerv', models.IntegerField(verbose_name='Забронированные места')),
                ('camera', models.ManyToManyField(to='myapp.camera')),
            ],
        ),
    ]
