# Generated by Django 4.1.2 on 2025-03-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='rezerv',
        ),
        migrations.AddField(
            model_name='page',
            name='rezervation',
            field=models.PositiveIntegerField(default=0, verbose_name='Забронированые места'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='full',
            field=models.PositiveIntegerField(verbose_name='Занятые места'),
        ),
    ]
