# Generated by Django 4.1.2 on 2025-03-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_page_rezerv_page_rezervation_alter_page_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ekleme zamani'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Isim'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='video',
            field=models.FileField(upload_to='videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='page',
            name='rezervation',
            field=models.PositiveIntegerField(verbose_name='Забронированные места'),
        ),
    ]
