# Generated by Django 4.1.2 on 2025-04-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_camera_time_alter_camera_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Парковка', 'verbose_name_plural': 'Парковки'},
        ),
    ]
