# Generated by Django 4.1.2 on 2025-04-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_camera_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Son güncelleme'),
        ),
    ]
