# Generated by Django 4.1.2 on 2025-04-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_page_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='video',
            field=models.ImageField(upload_to='videos/', verbose_name='Video'),
        ),
    ]
